version: "3"
services:
  undetected-chromedriver:
    build:
      context: .
      dockerfile: Dockerfile
    image: undetected-chromedriver
    container_name: undetected-chromedriver
    # command: "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf && <some command goes here>"
    ports:
      - 5900:5900
